apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: monetization-developer-password
  namespace: api-monetization-identity
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  length: 32
  digits: 8
  symbols: 0
  allowRepeat: true
  secretKeys:
    - portal-developer-password
    - developer-automation-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monetization-developer-credentials
  namespace: api-monetization-identity
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  refreshPolicy: CreatedOnce
  target:
    name: monetization-developer-credentials
    creationPolicy: Orphan
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: monetization-developer-password
