apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: grafana-keycloak-client-password
  namespace: api-monetization-identity
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  length: 48
  digits: 8
  symbols: 0
  allowRepeat: true
  secretKeys:
    - client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-keycloak-client
  namespace: api-monetization-identity
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  refreshPolicy: CreatedOnce
  target:
    name: grafana-keycloak-client
    creationPolicy: Orphan
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: grafana-keycloak-client-password
