apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: demo-inventory-api-key
  namespace: api-monetization-apps
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  length: 48
  digits: 8
  symbols: 0
  allowRepeat: true
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: demo-inventory-api-key
  namespace: api-monetization-apps
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  refreshPolicy: CreatedOnce
  target:
    name: demo-inventory-api-key
    creationPolicy: Orphan
    immutable: true
    template:
      engineVersion: v2
      metadata:
        labels:
          devportal.kuadrant.io/apiproduct: inventory-api
        annotations:
          secret.kuadrant.io/user-id: demo-company
      data:
        api_key: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: demo-inventory-api-key
