apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: keycloak-demo-client-passwords
  namespace: api-monetization-identity
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  length: 48
  digits: 8
  symbols: 0
  allowRepeat: true
  secretKeys:
    - free-client-secret
    - developer-client-secret
    - business-client-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-demo-clients
  namespace: api-monetization-identity
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  refreshPolicy: CreatedOnce
  target:
    name: keycloak-demo-clients
    creationPolicy: Orphan
    immutable: true
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: keycloak-demo-client-passwords

