apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - keycloak-db.yaml
  - keycloak-clients.yaml
  - grafana-identity.yaml
  - rhdh-identity.yaml
  - portal-identity.yaml
  - developer-identity.yaml
  - owner-approval-identity.yaml
  - subscriptions-db.yaml
  - inventory-api-key.yaml
