FROM registry.access.redhat.com/ubi9/openjdk-21:1.24-3 AS builder
WORKDIR /home/jboss/project
COPY pom.xml ./
COPY src/ src/
RUN mvn -B -DskipTests package

FROM registry.access.redhat.com/ubi9/openjdk-21-runtime:1.24-3
WORKDIR /deployments
COPY --from=builder /home/jboss/project/target/quarkus-app/lib/ lib/
COPY --from=builder /home/jboss/project/target/quarkus-app/*.jar ./
COPY --from=builder /home/jboss/project/target/quarkus-app/app/ app/
COPY --from=builder /home/jboss/project/target/quarkus-app/quarkus/ quarkus/
USER 185
EXPOSE 8080 8082
ENTRYPOINT ["java", "-jar", "quarkus-run.jar"]
