apiVersion: operator.openshift.io/v1alpha1
kind: ExternalSecretsConfig
metadata:
  name: cluster
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: api-monetization
spec: {}

