apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: api-monetization
  namespace: api-monetization-gateway
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    networking.istio.io/service-type: ClusterIP
  labels:
    app.kubernetes.io/name: api-monetization-gateway
    app.kubernetes.io/part-of: api-monetization
    kuadrant.io/gateway: "true"
spec:
  gatewayClassName: openshift-default
  listeners:
    - name: http
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              api-monetization.io/gateway-access: "true"
