apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-mode.yaml
  - gateway.yaml
  - openshift-routes.yaml
  - route-hosts.yaml
  - default-auth-policy.yaml
  - inventory-routes.yaml
  - inventory-auth-policies.yaml
  - inventory-plan-policy.yaml
  - inventory-jwt-rate-limits.yaml
  - openapi-readiness.yaml
  - inventory-api-product.yaml
  - demo-api-key.yaml
  - portal-rbac.yaml
