quarkus.http.port=8080
quarkus.application.name=${{ values.name }}
camel.main.name=${{ values.name }}
camel.main.routes-include-pattern=classpath:routes/*.camel.yaml
quarkus.micrometer.export.prometheus.path=/q/metrics

