apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-monetization-inventory
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "40"
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  project: api-monetization
  source:
    repoURL: https://github.com/arencloud/api-monetization-demo.git
    targetRevision: main
    path: applications/inventory
  destination:
    server: https://kubernetes.default.svc
    namespace: api-monetization-apps
  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: inventory-api
      namespace: api-monetization-apps
      jqPathExpressions:
        - .spec.template.spec.containers[] | select(.name == "inventory-api").image
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 15s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
