apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-monetization-openshift-ai
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "25"
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  project: api-monetization
  source:
    repoURL: https://github.com/arencloud/api-monetization-demo.git
    targetRevision: main
    path: platform/openshift-ai
  destination:
    server: https://kubernetes.default.svc
    namespace: redhat-ods-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 30
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true

