app:
  title: API Monetization Developer Hub
  baseUrl: ${RHDH_BASE_URL}

organization:
  name: API Monetization

backend:
  baseUrl: ${RHDH_BASE_URL}
  cors:
    origin: ${RHDH_BASE_URL}
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  auth:
    externalAccess:
      - type: legacy
        options:
          subject: legacy-default-config
          secret: ${BACKEND_SECRET}
  database:
    client: pg
    pluginDivisionMode: schema
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      database: ${POSTGRES_DB}
      ssl:
        rejectUnauthorized: false

auth:
  environment: production
  session:
    secret: ${SESSION_SECRET}
  providers:
    oidc:
      production:
        metadataUrl: ${KEYCLOAK_BASE_URL}
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        prompt: auto
        signIn:
          resolvers:
            - resolver: oidcSubClaimMatchingKeycloakUserId

signInPage: oidc

kubernetes: null

integrations:
  github:
    - host: github.com

catalog:
  rules:
    - allow:
        - API
        - APIProduct
        - Component
        - Domain
        - Group
        - Location
        - Resource
        - System
        - Template
        - User
  providers:
    keycloakOrg:
      default:
        baseUrl: ${KEYCLOAK_SERVER_URL}
        loginRealm: ${KEYCLOAK_LOGIN_REALM}
        realm: ${KEYCLOAK_REALM}
        clientId: ${KEYCLOAK_CLIENT_ID}
        clientSecret: ${KEYCLOAK_CLIENT_SECRET}
        schedule:
          frequency: {minutes: 1}
          initialDelay: {seconds: 15}
          timeout: {minutes: 1}
  locations:
    - type: url
      target: https://github.com/arencloud/api-monetization-demo/blob/golden-path-test/golden-paths/api-interface/template.yaml
      rules:
        - allow: [Template]
    - type: url
      target: https://github.com/arencloud/api-monetization-demo/blob/golden-path-test/golden-paths/camel-api-integration/template.yaml
      rules:
        - allow: [Template]

scaffolder:
  defaultAuthor:
    name: API Monetization Developer Hub
    email: api-platform@example.invalid
  defaultCommitMessage: Bootstrap from an API-owner Golden Path

permission:
  enabled: true
  rbac:
    policies-csv-file: /opt/app-root/etc/rbac-policy.csv
    policyFileReload: true

dynamicPlugins:
  frontend:
    default.main-menu-items:
      menuItems:
        default.apis:
          title: APIs
          icon: extension
          to: monetized-apis
          priority: 70
          enabled: true
        default.create:
          title: Golden Paths
          icon: add
          to: create
          priority: 65
          enabled: true

apiMonetization:
  controlBaseUrl: http://monetization-control.api-monetization-data.svc.cluster.local:8080
