apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - credentials.yaml
  - identity-secret-store.yaml
  - database.yaml
  - runtime-config.yaml
  - kuadrant-access.yaml
  - backstage.yaml
configMapGenerator:
  - name: api-monetization-rhdh-app-config
    namespace: api-monetization-developer-hub
    files:
      - app-config.yaml
  - name: api-monetization-rhdh-dynamic-plugins
    namespace: api-monetization-developer-hub
    files:
      - dynamic-plugins.yaml
  - name: api-monetization-rhdh-rbac-policies
    namespace: api-monetization-developer-hub
    files:
      - rbac-policy.csv
generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: api-monetization
