apiVersion: v1
kind: Secret
metadata:
  name: api-monetization-rhdh-service-account-token
  namespace: api-monetization-developer-hub
  annotations:
    kubernetes.io/service-account.name: api-monetization-rhdh
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/part-of: api-monetization
type: kubernetes.io/service-account-token
