apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - theme-build.yaml
  - theme-source-build.yaml
  - keycloak.yaml
  - route.yaml
  - realm-import.yaml
  - portal-identity.yaml
configMapGenerator:
  - name: api-monetization-identity-hook-trigger
    namespace: api-monetization-identity
    files:
      - portal-identity.yaml
      - theme/Containerfile
      - theme/api-monetization/login/theme.properties
      - theme/api-monetization/login/messages/messages_en.properties
      - theme/api-monetization/login/resources/css/login.css
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "5"
      labels:
        app.kubernetes.io/name: api-monetization-identity-hook-trigger
        app.kubernetes.io/part-of: api-monetization
