apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
  namespace: api-monetization-apps
  annotations:
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"payments-api:demo","namespace":"api-monetization-apps"},"fieldPath":"spec.template.spec.containers[?(@.name==\"payments-api\")].image","paused":false}]
  labels:
    app.kubernetes.io/name: payments-api
    app.kubernetes.io/part-of: api-monetization
    app.kubernetes.io/component: backend-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: payments-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payments-api
        app.kubernetes.io/part-of: api-monetization
        app.kubernetes.io/component: backend-api
        sidecar.istio.io/inject: "true"
    spec:
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        seccompProfile: {type: RuntimeDefault}
      containers:
        - name: payments-api
          image: image-registry.openshift-image-registry.svc:5000/api-monetization-apps/payments-api:demo
          imagePullPolicy: Always
          ports:
            - {name: http, containerPort: 8080}
            - {name: openapi, containerPort: 8082}
          env:
            - name: USAGE_SINK_URL
              value: http://monetization-control.api-monetization-data.svc.cluster.local:8081/internal/usage
          readinessProbe:
            httpGet: {path: /readyz, port: http}
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet: {path: /healthz, port: http}
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests: {cpu: 50m, memory: 64Mi}
            limits: {cpu: 500m, memory: 256Mi}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {drop: [ALL]}
            readOnlyRootFilesystem: true
          volumeMounts:
            - name: openapi
              mountPath: /opt/app-root/src/openapi.yaml
              subPath: openapi.yaml
              readOnly: true
      volumes:
        - name: openapi
          configMap: {name: payments-api-openapi}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels: {app.kubernetes.io/name: payments-api}
