apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: payments-api
  namespace: api-monetization-apps
  labels:
    app.kubernetes.io/name: payments-api
    app.kubernetes.io/part-of: api-monetization
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payments-api
  podMetricsEndpoints:
    - {port: http, path: /metrics, interval: 15s}
