apiVersion: v1
kind: Service
metadata:
  name: ai-chat-model-mtls
  namespace: api-monetization-ai
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/name: ai-chat-model-mtls
    app.kubernetes.io/part-of: api-monetization
    app.kubernetes.io/component: cpu-model-serving
spec:
  selector:
    serving.kserve.io/inferenceservice: ai-chat
  ports:
    - name: http-model
      port: 8080
      targetPort: 8080
      protocol: TCP
