apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-monetization-secret-reader
  namespace: api-monetization-observability
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  labels:
    app.kubernetes.io/part-of: api-monetization
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: api-monetization-grafana-client-reader
  namespace: api-monetization-identity
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  labels:
    app.kubernetes.io/part-of: api-monetization
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - grafana-keycloak-client
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-monetization-grafana-client-reader
  namespace: api-monetization-identity
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  labels:
    app.kubernetes.io/part-of: api-monetization
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-monetization-grafana-client-reader
subjects:
  - kind: ServiceAccount
    name: api-monetization-secret-reader
    namespace: api-monetization-observability
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-monetization-secret-store-reviewer
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  labels:
    app.kubernetes.io/part-of: api-monetization
rules:
  - apiGroups:
      - authorization.k8s.io
    resources:
      - selfsubjectrulesreviews
    verbs:
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-monetization-secret-store-reviewer
  annotations:
    argocd.argoproj.io/sync-wave: "-6"
  labels:
    app.kubernetes.io/part-of: api-monetization
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-monetization-secret-store-reviewer
subjects:
  - kind: ServiceAccount
    name: api-monetization-secret-reader
    namespace: api-monetization-observability
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: api-monetization-identity
  namespace: api-monetization-observability
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  provider:
    kubernetes:
      remoteNamespace: api-monetization-identity
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: api-monetization-secret-reader
