apiVersion: tempo.grafana.com/v1alpha1
kind: TempoMonolithic
metadata:
  name: api-monetization
  namespace: api-monetization-observability
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: api-monetization
spec:
  storage:
    traces:
      backend: memory
      size: 1Gi
  jaegerui:
    enabled: true
    route:
      enabled: true
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi
