apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - build.yaml
  - source-build.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - route.yaml
  - monitoring.yaml
configMapGenerator:
  - name: monetization-control-source-trigger
    namespace: api-monetization-data
    files:
      - Containerfile
      - auth.go
      - billing.go
      - main.go
      - main_test.go
      - migrations.go
      - selfservice.go
      - web/index.html
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      labels:
        app.kubernetes.io/name: monetization-control-source-trigger
        app.kubernetes.io/part-of: api-monetization
