apiVersion: v1
kind: ServiceAccount
metadata:
  name: monetization-control
  namespace: api-monetization-data
  labels:
    app.kubernetes.io/part-of: api-monetization
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monetization-credential-manager
  namespace: api-monetization-apps
  labels:
    app.kubernetes.io/part-of: api-monetization
rules:
  - apiGroups:
      - devportal.kuadrant.io
    resources:
      - apikeys
    verbs:
      - create
      - delete
      - get
      - patch
  - apiGroups:
      - generators.external-secrets.io
    resources:
      - passwords
    verbs:
      - create
      - delete
      - get
  - apiGroups:
      - external-secrets.io
    resources:
      - externalsecrets
    verbs:
      - create
      - delete
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - delete
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monetization-control-credential-manager
  namespace: api-monetization-apps
  labels:
    app.kubernetes.io/part-of: api-monetization
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monetization-credential-manager
subjects:
  - kind: ServiceAccount
    name: monetization-control
    namespace: api-monetization-data
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: monetization-keycloak-route-reader
  namespace: api-monetization-identity
  labels:
    app.kubernetes.io/part-of: api-monetization
rules:
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    resourceNames:
      - api-monetization-keycloak
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: monetization-control-keycloak-route-reader
  namespace: api-monetization-identity
  labels:
    app.kubernetes.io/part-of: api-monetization
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: monetization-keycloak-route-reader
subjects:
  - kind: ServiceAccount
    name: monetization-control
    namespace: api-monetization-data
