apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - build.yaml
  - source-build.yaml
  - deployment.yaml
  - service.yaml
  - monitoring.yaml
configMapGenerator:
  - name: ai-chat-api-openapi
    namespace: api-monetization-apps
    files:
      - openapi/api-key.yaml
      - openapi/keycloak-jwt.yaml
    options:
      disableNameSuffixHash: true
      labels:
        app.kubernetes.io/name: ai-chat-api
        app.kubernetes.io/part-of: api-monetization
  - name: ai-chat-api-source-trigger
    namespace: api-monetization-apps
    files:
      - Containerfile
      - main.go
      - main_test.go
    options:
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
      labels:
        app.kubernetes.io/name: ai-chat-api-source-trigger
        app.kubernetes.io/part-of: api-monetization
generatorOptions:
  labels:
    app.kubernetes.io/part-of: api-monetization
